In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Data Tidying and Cleaning Demos 3
## Live Demos

In [3]:
billboard_data = pd.read_csv("02.Data-Tidying-and-Cleaning-Materials/billboard.csv")

In [4]:
billboard_data

,year,artist,track,time,date.entered,wk1,wk2,wk3,wk4,wk5,...,wk67,wk68,wk69,wk70,wk71,wk72,wk73,wk74,wk75,wk76
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,87,82.0,72.0,77.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,91,87.0,92.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,81,70.0,68.0,67.0,66.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,3 Doors Down,Loser,4:24,2000-10-21,76,76.0,72.0,69.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,57,34.0,25.0,17.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Yankee Grey,Another Nine Minutes,3:10,2000-04-29,86,83.0,77.0,74.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Yearwood, Trisha",Real Live Woman,3:55,2000-04-01,85,83.0,83.0,82.0,81.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Ying Yang Twins,Whistle While You Tw...,4:19,2000-03-18,95,94.0,91.0,85.0,84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,Zombie Nation,Kernkraft 400,3:30,2000-09-02,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,matchbox twenty,Bent,4:12,2000-04-29,60,37.0,29.0,24.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
billboard_data[["wk1", "wk2", "wk3"]].dtypes

wk1      int64
wk2    float64
wk3    float64
dtype: object

In [10]:
billboard_data[billboard_data.wk2.isna()]

,year,artist,track,time,date.entered,wk1,wk2,wk3,wk4,wk5,...,wk67,wk68,wk69,wk70,wk71,wk72,wk73,wk74,wk75,wk76
17,2000,Anastacia,I'm Outta Love,4:01,2000-04-01,92,NaN,NaN,95.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,2000,"Estefan, Gloria",No Me Dejes De Quere...,3:25,2000-06-10,77,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,2000,Fragma,Toca's Miracle,3:22,2000-10-28,99,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,2000,Ghostface Killah,Cherchez LaGhost,3:04,2000-08-05,98,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,2000,Master P,Souljas,3:33,2000-11-18,98,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
billboard_data = billboard_data.melt(
    id_vars = ["year", "artist", "track", "time", "date.entered"], 
    var_name = "week", 
    value_name = "position"
)

In [14]:
billboard_data

,year,artist,track,time,date.entered,week,position
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,wk1,87.0
1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,wk1,91.0
2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,wk1,81.0
3,2000,3 Doors Down,Loser,4:24,2000-10-21,wk1,76.0
4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,wk1,57.0
...,...,...,...,...,...,...,...
24087,2000,Yankee Grey,Another Nine Minutes,3:10,2000-04-29,wk76,NaN
24088,2000,"Yearwood, Trisha",Real Live Woman,3:55,2000-04-01,wk76,NaN
24089,2000,Ying Yang Twins,Whistle While You Tw...,4:19,2000-03-18,wk76,NaN
24090,2000,Zombie Nation,Kernkraft 400,3:30,2000-09-02,wk76,NaN
24091,2000,matchbox twenty,Bent,4:12,2000-04-29,wk76,NaN

In [15]:
billboard_data.week.value_counts()

week
wk1     317
wk2     317
wk3     317
wk4     317
wk5     317
       ...
wk72    317
wk73    317
wk74    317
wk75    317
wk76    317
Name: count, Length: 76, dtype: int64

In [18]:
billboard_data.week = billboard_data.week.str.slice(2).astype(int)

In [19]:
billboard_data.week

0         1
1         1
2         1
3         1
4         1
         ..
24087    76
24088    76
24089    76
24090    76
24091    76
Name: week, Length: 24092, dtype: int64

In [21]:
billboard_data.dtypes

year              int64
artist           object
track            object
time             object
date.entered     object
week              int64
position        float64
dtype: object

In [23]:
billboard_data["date.entered"] = pd.to_datetime(billboard_data["date.entered"])

In [24]:
billboard_data

,year,artist,track,time,date.entered,week,position
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,1,87.0
1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,1,91.0
2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,1,81.0
3,2000,3 Doors Down,Loser,4:24,2000-10-21,1,76.0
4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,1,57.0
...,...,...,...,...,...,...,...
24087,2000,Yankee Grey,Another Nine Minutes,3:10,2000-04-29,76,NaN
24088,2000,"Yearwood, Trisha",Real Live Woman,3:55,2000-04-01,76,NaN
24089,2000,Ying Yang Twins,Whistle While You Tw...,4:19,2000-03-18,76,NaN
24090,2000,Zombie Nation,Kernkraft 400,3:30,2000-09-02,76,NaN
24091,2000,matchbox twenty,Bent,4:12,2000-04-29,76,NaN

In [25]:
billboard_data = billboard_data.dropna()

In [26]:
billboard_data

,year,artist,track,time,date.entered,week,position
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,1,87.0
1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,1,91.0
2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,1,81.0
3,2000,3 Doors Down,Loser,4:24,2000-10-21,1,76.0
4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,1,57.0
...,...,...,...,...,...,...,...
19716,2000,Creed,Higher,5:16,1999-09-11,63,50.0
19833,2000,Lonestar,Amazed,4:25,1999-06-05,63,45.0
20033,2000,Creed,Higher,5:16,1999-09-11,64,50.0
20150,2000,Lonestar,Amazed,4:25,1999-06-05,64,50.0
20350,2000,Creed,Higher,5:16,1999-09-11,65,49.0

In [27]:
pd.Timedelta("7 days")

Timedelta('7 days 00:00:00')

In [31]:
billboard_data["date.entered"] + pd.Timedelta(f"{} days")

0       2000-02-26
1       2000-09-02
2       2000-04-08
3       2000-10-21
4       2000-04-15
           ...
19716   1999-09-11
19833   1999-06-05
20033   1999-09-11
20150   1999-06-05
20350   1999-09-11
Name: date.entered, Length: 5307, dtype: datetime64[ns]

In [34]:
f"{(billboard_data.week - 1) * 7}"

'0          0\n1          0\n2          0\n3          0\n4          0\n        ... \n19716    434\n19833    434\n20033    441\n20150    441\n20350    448\nName: week, Length: 5307, dtype: int64'